#!/usr/bin/env python3
"""Generate data/pokemon.luau from a checkout of jakobhoeg/vscode-pokemon.

Usage: python tools/gen-data.py PATH_TO_VSCODE_POKEMON [--out FILE]

Reads src/common/pokemon-data.ts and the sprite directories under media/gen1..5,
keeps the species that have a default_idle_8fps.gif, and writes a Luau module
sorting them by (generation, id, directory name).
"""

import argparse
import pathlib
import re
import sys

ENTRY = re.compile(r"^  ([A-Za-z0-9_]+): \{\n(.*?)\n  \},", re.M | re.S)
ID = re.compile(r"\bid: (\d+)")
NAME = re.compile(r"""\bname: (['"])(.*?)\1""")
GEN = re.compile(r"generation: PokemonGeneration\.Gen(\d+)")
SIZE = re.compile(r"originalSpriteSize: (\d+)")
SHINY = re.compile(r"possibleColors: \[([^\]]*)\]")
EXTRA = re.compile(r"extraSprites: \[([^\]]*)\]")

# gen -> pokedex generations the sprite folders cover, in the extension's order
GENS = [1, 2, 3, 4, 5]


def luau_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("repo", type=pathlib.Path)
    ap.add_argument("--out", type=pathlib.Path, default=pathlib.Path("data/pokemon.luau"))
    args = ap.parse_args()

    src = args.repo / "src" / "common" / "pokemon-data.ts"
    text = src.read_text(encoding="utf-8")

    rows = []
    for m in ENTRY.finditer(text):
        key, body = m.group(1), m.group(2)
        idm, namem, genm = ID.search(body), NAME.search(body), GEN.search(body)
        if not (idm and namem and genm):
            continue
        gen = int(genm.group(1))
        if gen not in GENS:
            continue
        folder = args.repo / "media" / f"gen{gen}" / key
        if not (folder / "default_idle_8fps.gif").is_file():
            continue
        shiny = bool(SHINY.search(body)) and "shiny" in SHINY.search(body).group(1)
        left = bool(EXTRA.search(body)) and "leftFacing" in EXTRA.search(body).group(1)
        size = int(SIZE.search(body).group(1)) if SIZE.search(body) else 32
        rows.append((gen, int(idm.group(1)), key, namem.group(2), shiny, left, size))

    rows.sort(key=lambda r: (r[0], r[1], r[2]))

    out = [
        "-- Generated by tools/gen-data.py from jakobhoeg/vscode-pokemon",
        "-- (src/common/pokemon-data.ts + media/gen1..5 sprite folders). Do not edit by hand.",
        "-- name: sprite folder, label: display name, id: pokedex number, gen: 1-5,",
        "-- shiny: shiny sprites exist, left: walk_left sprites exist, size: native sprite px.",
        "return {",
    ]
    for gen, pid, key, label, shiny, left, size in rows:
        out.append(
            f'\t{{ name = "{key}", label = "{luau_escape(label)}", id = {pid}, '
            f"gen = {gen}, shiny = {str(shiny).lower()}, left = {str(left).lower()}, size = {size} }},"
        )
    out.append("}")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{len(rows)} species -> {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
